/**
 * server/qr-crypto.ts
 *
 * Cryptographic QR payload generation and verification.
 *
 * Architecture:
 *   - QR payload = JSON { sessionId, eventId, timestamp, nonce, signature }
 *   - Signature = HMAC-SHA256(sessionId|eventId|timestamp|nonce, secret)
 *   - Nonce = crypto.randomUUID() — stored in Firestore with TTL
 *   - Secret is a 256-bit key stored in the session's Firestore subcollection
 *
 * Security guarantees:
 *   - Students cannot forge QR codes (they don't know the HMAC secret)
 *   - Photographed QR codes expire (timestamp + rotation interval)
 *   - Replay attacks prevented (nonce is single-use)
 *   - Payload is compact for QR rendering (Base64-encoded JSON)
 */

import crypto from 'crypto';

export interface QrPayload {
  sessionId: string;
  eventId: string;
  timestamp: number;   // Unix ms
  nonce: string;       // UUID
  signature: string;   // HMAC-SHA256 hex
  v?: number;          // version
}

/**
 * Compute HMAC-SHA256 signature for QR payload fields.
 */
function computeSignature(sessionId: string, eventId: string, timestamp: number, nonce: string, secret: string): string {
  const message = `${sessionId}|${eventId}|${timestamp}|${nonce}`;
  return crypto
    .createHmac('sha256', secret)
    .update(message)
    .digest('hex');
}

/**
 * Generate a new QR payload with cryptographic signature.
 *
 * Called by the admin QR generation endpoint.
 * The nonce must be stored in Firestore by the caller.
 */
export function generateQrPayload(sessionId: string, eventId: string, secret: string): QrPayload {
  const timestamp = Date.now();
  const nonce = crypto.randomUUID();
  const signature = computeSignature(sessionId, eventId, timestamp, nonce, secret);

  return {
    sessionId,
    eventId,
    timestamp,
    nonce,
    signature,
    v: 1
  };
}

/**
 * Verify a QR payload's cryptographic signature.
 *
 * Returns true if the signature is valid (payload was generated by our server).
 * Does NOT check timestamp freshness or nonce usage — those are checked separately.
 */
export function verifyQrSignature(payload: QrPayload, secret: string): boolean {
  const expected = computeSignature(
    payload.sessionId,
    payload.eventId,
    payload.timestamp,
    payload.nonce,
    secret
  );

  // Timing-safe comparison to prevent timing attacks
  try {
    return crypto.timingSafeEqual(
      Buffer.from(expected, 'hex'),
      Buffer.from(payload.signature, 'hex'),
    );
  } catch {
    // If lengths differ or input is malformed, comparison throws
    return false;
  }
}

/**
 * Encode a QR payload as a compact Base64 string for QR code rendering.
 */
export function encodeQrPayload(payload: QrPayload): string {
  const json = JSON.stringify(payload);
  return Buffer.from(json).toString('base64url');
}

/**
 * Decode a Base64-encoded QR payload string back to a QrPayload object.
 * Returns null if the string is malformed.
 */
export function decodeQrPayload(encoded: string): QrPayload | null {
  try {
    const json = Buffer.from(encoded, 'base64url').toString('utf-8');
    const parsed = JSON.parse(json);

    // Validate required fields
    if (
      typeof parsed.sessionId !== 'string' ||
      typeof parsed.eventId !== 'string' ||
      typeof parsed.timestamp !== 'number' ||
      typeof parsed.nonce !== 'string' ||
      typeof parsed.signature !== 'string'
    ) {
      return null;
    }

    return parsed as QrPayload;
  } catch {
    return null;
  }
}

/**
 * Check if a QR payload has expired based on the rotation interval.
 *
 * @param payload - The QR payload to check
 * @param rotationIntervalSeconds - QR rotation interval in seconds
 * @param toleranceSeconds - Extra tolerance for network latency (default 10s)
 */
export function isQrExpired(
  payload: QrPayload,
  rotationIntervalSeconds: number,
  toleranceSeconds: number = 10,
): boolean {
  const maxAgeMs = (rotationIntervalSeconds + toleranceSeconds) * 1000;
  return Date.now() - payload.timestamp > maxAgeMs;
}
