/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyPassRouteImport } from './routes/my-pass'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanTokenRouteImport } from './routes/scan.$token'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminScannerRouteImport } from './routes/admin.scanner'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClubsRouteImport } from './routes/admin.clubs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPassRoute = MyPassRouteImport.update({
  id: '/my-pass',
  path: '/my-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanTokenRoute = ScanTokenRouteImport.update({
  id: '/scan/$token',
  path: '/scan/$token',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/scan.$token.lazy').then((d) => d.Route))
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.students.lazy').then((d) => d.Route),
)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScannerRoute = AdminScannerRouteImport.update({
  id: '/admin/scanner',
  path: '/admin/scanner',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.scanner.lazy').then((d) => d.Route))
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.documents.lazy').then((d) => d.Route),
)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.dashboard.lazy').then((d) => d.Route),
)
const AdminClubsRoute = AdminClubsRouteImport.update({
  id: '/admin/clubs',
  path: '/admin/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.analytics.lazy').then((d) => d.Route),
)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/clubs': typeof ClubsRoute
  '/cookies': typeof CookiesRoute
  '/help': typeof HelpRoute
  '/my-pass': typeof MyPassRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/students': typeof AdminStudentsRoute
  '/scan/$token': typeof ScanTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/clubs': typeof ClubsRoute
  '/cookies': typeof CookiesRoute
  '/help': typeof HelpRoute
  '/my-pass': typeof MyPassRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/students': typeof AdminStudentsRoute
  '/scan/$token': typeof ScanTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/clubs': typeof ClubsRoute
  '/cookies': typeof CookiesRoute
  '/help': typeof HelpRoute
  '/my-pass': typeof MyPassRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/scanner': typeof AdminScannerRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/students': typeof AdminStudentsRoute
  '/scan/$token': typeof ScanTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/clubs'
    | '/cookies'
    | '/help'
    | '/my-pass'
    | '/privacy'
    | '/register'
    | '/schedule'
    | '/terms'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/login'
    | '/admin/scanner'
    | '/admin/schedule'
    | '/admin/students'
    | '/scan/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/attendance'
    | '/clubs'
    | '/cookies'
    | '/help'
    | '/my-pass'
    | '/privacy'
    | '/register'
    | '/schedule'
    | '/terms'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/login'
    | '/admin/scanner'
    | '/admin/schedule'
    | '/admin/students'
    | '/scan/$token'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/attendance'
    | '/clubs'
    | '/cookies'
    | '/help'
    | '/my-pass'
    | '/privacy'
    | '/register'
    | '/schedule'
    | '/terms'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/clubs'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/events'
    | '/admin/login'
    | '/admin/scanner'
    | '/admin/schedule'
    | '/admin/students'
    | '/scan/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  ClubsRoute: typeof ClubsRoute
  CookiesRoute: typeof CookiesRoute
  HelpRoute: typeof HelpRoute
  MyPassRoute: typeof MyPassRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ScheduleRoute: typeof ScheduleRoute
  TermsRoute: typeof TermsRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminClubsRoute: typeof AdminClubsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminScannerRoute: typeof AdminScannerRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  ScanTokenRoute: typeof ScanTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pass': {
      id: '/my-pass'
      path: '/my-pass'
      fullPath: '/my-pass'
      preLoaderRoute: typeof MyPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$token': {
      id: '/scan/$token'
      path: '/scan/$token'
      fullPath: '/scan/$token'
      preLoaderRoute: typeof ScanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scanner': {
      id: '/admin/scanner'
      path: '/admin/scanner'
      fullPath: '/admin/scanner'
      preLoaderRoute: typeof AdminScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clubs': {
      id: '/admin/clubs'
      path: '/admin/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AdminClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  ClubsRoute: ClubsRoute,
  CookiesRoute: CookiesRoute,
  HelpRoute: HelpRoute,
  MyPassRoute: MyPassRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ScheduleRoute: ScheduleRoute,
  TermsRoute: TermsRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminClubsRoute: AdminClubsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminScannerRoute: AdminScannerRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  ScanTokenRoute: ScanTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
