/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventAttendEventIdRouteImport } from './routes/event-attend.$eventId'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsLazyRouteImport = createFileRoute('/terms')()
const ScheduleLazyRouteImport = createFileRoute('/schedule')()
const PrivacyLazyRouteImport = createFileRoute('/privacy')()
const MyPassLazyRouteImport = createFileRoute('/my-pass')()
const HelpLazyRouteImport = createFileRoute('/help')()
const CookiesLazyRouteImport = createFileRoute('/cookies')()
const ClubsLazyRouteImport = createFileRoute('/clubs')()
const CampusLazyRouteImport = createFileRoute('/campus')()
const AttendanceLazyRouteImport = createFileRoute('/attendance')()
const AnnouncementsLazyRouteImport = createFileRoute('/announcements')()
const AdminScheduleLazyRouteImport = createFileRoute('/admin/schedule')()
const AdminRoomsLazyRouteImport = createFileRoute('/admin/rooms')()
const AdminMediaLazyRouteImport = createFileRoute('/admin/media')()
const AdminLoginLazyRouteImport = createFileRoute('/admin/login')()
const AdminEventsLazyRouteImport = createFileRoute('/admin/events')()
const AdminDatasetsLazyRouteImport = createFileRoute('/admin/datasets')()
const AdminClubsLazyRouteImport = createFileRoute('/admin/clubs')()
const AdminAttendanceLazyRouteImport = createFileRoute('/admin/attendance')()
const AdminAnnouncementsLazyRouteImport = createFileRoute(
  '/admin/announcements',
)()
const AdminActivityLazyRouteImport = createFileRoute('/admin/activity')()

const TermsLazyRoute = TermsLazyRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const ScheduleLazyRoute = ScheduleLazyRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/schedule.lazy').then((d) => d.Route))
const PrivacyLazyRoute = PrivacyLazyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const MyPassLazyRoute = MyPassLazyRouteImport.update({
  id: '/my-pass',
  path: '/my-pass',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/my-pass.lazy').then((d) => d.Route))
const HelpLazyRoute = HelpLazyRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/help.lazy').then((d) => d.Route))
const CookiesLazyRoute = CookiesLazyRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cookies.lazy').then((d) => d.Route))
const ClubsLazyRoute = ClubsLazyRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/clubs.lazy').then((d) => d.Route))
const CampusLazyRoute = CampusLazyRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/campus.lazy').then((d) => d.Route))
const AttendanceLazyRoute = AttendanceLazyRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/attendance.lazy').then((d) => d.Route))
const AnnouncementsLazyRoute = AnnouncementsLazyRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/announcements.lazy').then((d) => d.Route))
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleLazyRoute = AdminScheduleLazyRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.schedule.lazy').then((d) => d.Route),
)
const AdminRoomsLazyRoute = AdminRoomsLazyRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.rooms.lazy').then((d) => d.Route))
const AdminMediaLazyRoute = AdminMediaLazyRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.media.lazy').then((d) => d.Route))
const AdminLoginLazyRoute = AdminLoginLazyRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.login.lazy').then((d) => d.Route))
const AdminEventsLazyRoute = AdminEventsLazyRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.events.lazy').then((d) => d.Route))
const AdminDatasetsLazyRoute = AdminDatasetsLazyRouteImport.update({
  id: '/admin/datasets',
  path: '/admin/datasets',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.datasets.lazy').then((d) => d.Route),
)
const AdminClubsLazyRoute = AdminClubsLazyRouteImport.update({
  id: '/admin/clubs',
  path: '/admin/clubs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.clubs.lazy').then((d) => d.Route))
const AdminAttendanceLazyRoute = AdminAttendanceLazyRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.attendance.lazy').then((d) => d.Route),
)
const AdminAnnouncementsLazyRoute = AdminAnnouncementsLazyRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.announcements.lazy').then((d) => d.Route),
)
const AdminActivityLazyRoute = AdminActivityLazyRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.activity.lazy').then((d) => d.Route),
)
const EventAttendEventIdRoute = EventAttendEventIdRouteImport.update({
  id: '/event-attend/$eventId',
  path: '/event-attend/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.students.lazy').then((d) => d.Route),
)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.documents.lazy').then((d) => d.Route),
)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.dashboard.lazy').then((d) => d.Route),
)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin.analytics.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/announcements': typeof AnnouncementsLazyRoute
  '/attendance': typeof AttendanceLazyRoute
  '/campus': typeof CampusLazyRoute
  '/clubs': typeof ClubsLazyRoute
  '/cookies': typeof CookiesLazyRoute
  '/help': typeof HelpLazyRoute
  '/my-pass': typeof MyPassLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/schedule': typeof ScheduleLazyRoute
  '/terms': typeof TermsLazyRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/event-attend/$eventId': typeof EventAttendEventIdRoute
  '/admin/activity': typeof AdminActivityLazyRoute
  '/admin/announcements': typeof AdminAnnouncementsLazyRoute
  '/admin/attendance': typeof AdminAttendanceLazyRoute
  '/admin/clubs': typeof AdminClubsLazyRoute
  '/admin/datasets': typeof AdminDatasetsLazyRoute
  '/admin/events': typeof AdminEventsLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/admin/media': typeof AdminMediaLazyRoute
  '/admin/rooms': typeof AdminRoomsLazyRoute
  '/admin/schedule': typeof AdminScheduleLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/announcements': typeof AnnouncementsLazyRoute
  '/attendance': typeof AttendanceLazyRoute
  '/campus': typeof CampusLazyRoute
  '/clubs': typeof ClubsLazyRoute
  '/cookies': typeof CookiesLazyRoute
  '/help': typeof HelpLazyRoute
  '/my-pass': typeof MyPassLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/schedule': typeof ScheduleLazyRoute
  '/terms': typeof TermsLazyRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/event-attend/$eventId': typeof EventAttendEventIdRoute
  '/admin/activity': typeof AdminActivityLazyRoute
  '/admin/announcements': typeof AdminAnnouncementsLazyRoute
  '/admin/attendance': typeof AdminAttendanceLazyRoute
  '/admin/clubs': typeof AdminClubsLazyRoute
  '/admin/datasets': typeof AdminDatasetsLazyRoute
  '/admin/events': typeof AdminEventsLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/admin/media': typeof AdminMediaLazyRoute
  '/admin/rooms': typeof AdminRoomsLazyRoute
  '/admin/schedule': typeof AdminScheduleLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/announcements': typeof AnnouncementsLazyRoute
  '/attendance': typeof AttendanceLazyRoute
  '/campus': typeof CampusLazyRoute
  '/clubs': typeof ClubsLazyRoute
  '/cookies': typeof CookiesLazyRoute
  '/help': typeof HelpLazyRoute
  '/my-pass': typeof MyPassLazyRoute
  '/privacy': typeof PrivacyLazyRoute
  '/schedule': typeof ScheduleLazyRoute
  '/terms': typeof TermsLazyRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/event-attend/$eventId': typeof EventAttendEventIdRoute
  '/admin/activity': typeof AdminActivityLazyRoute
  '/admin/announcements': typeof AdminAnnouncementsLazyRoute
  '/admin/attendance': typeof AdminAttendanceLazyRoute
  '/admin/clubs': typeof AdminClubsLazyRoute
  '/admin/datasets': typeof AdminDatasetsLazyRoute
  '/admin/events': typeof AdminEventsLazyRoute
  '/admin/login': typeof AdminLoginLazyRoute
  '/admin/media': typeof AdminMediaLazyRoute
  '/admin/rooms': typeof AdminRoomsLazyRoute
  '/admin/schedule': typeof AdminScheduleLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/announcements'
    | '/attendance'
    | '/campus'
    | '/clubs'
    | '/cookies'
    | '/help'
    | '/my-pass'
    | '/privacy'
    | '/schedule'
    | '/terms'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/students'
    | '/event-attend/$eventId'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/clubs'
    | '/admin/datasets'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/rooms'
    | '/admin/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/announcements'
    | '/attendance'
    | '/campus'
    | '/clubs'
    | '/cookies'
    | '/help'
    | '/my-pass'
    | '/privacy'
    | '/schedule'
    | '/terms'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/students'
    | '/event-attend/$eventId'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/clubs'
    | '/admin/datasets'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/rooms'
    | '/admin/schedule'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/announcements'
    | '/attendance'
    | '/campus'
    | '/clubs'
    | '/cookies'
    | '/help'
    | '/my-pass'
    | '/privacy'
    | '/schedule'
    | '/terms'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/students'
    | '/event-attend/$eventId'
    | '/admin/activity'
    | '/admin/announcements'
    | '/admin/attendance'
    | '/admin/clubs'
    | '/admin/datasets'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/rooms'
    | '/admin/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AnnouncementsLazyRoute: typeof AnnouncementsLazyRoute
  AttendanceLazyRoute: typeof AttendanceLazyRoute
  CampusLazyRoute: typeof CampusLazyRoute
  ClubsLazyRoute: typeof ClubsLazyRoute
  CookiesLazyRoute: typeof CookiesLazyRoute
  HelpLazyRoute: typeof HelpLazyRoute
  MyPassLazyRoute: typeof MyPassLazyRoute
  PrivacyLazyRoute: typeof PrivacyLazyRoute
  ScheduleLazyRoute: typeof ScheduleLazyRoute
  TermsLazyRoute: typeof TermsLazyRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  EventAttendEventIdRoute: typeof EventAttendEventIdRoute
  AdminActivityLazyRoute: typeof AdminActivityLazyRoute
  AdminAnnouncementsLazyRoute: typeof AdminAnnouncementsLazyRoute
  AdminAttendanceLazyRoute: typeof AdminAttendanceLazyRoute
  AdminClubsLazyRoute: typeof AdminClubsLazyRoute
  AdminDatasetsLazyRoute: typeof AdminDatasetsLazyRoute
  AdminEventsLazyRoute: typeof AdminEventsLazyRoute
  AdminLoginLazyRoute: typeof AdminLoginLazyRoute
  AdminMediaLazyRoute: typeof AdminMediaLazyRoute
  AdminRoomsLazyRoute: typeof AdminRoomsLazyRoute
  AdminScheduleLazyRoute: typeof AdminScheduleLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pass': {
      id: '/my-pass'
      path: '/my-pass'
      fullPath: '/my-pass'
      preLoaderRoute: typeof MyPassLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/datasets': {
      id: '/admin/datasets'
      path: '/admin/datasets'
      fullPath: '/admin/datasets'
      preLoaderRoute: typeof AdminDatasetsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clubs': {
      id: '/admin/clubs'
      path: '/admin/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AdminClubsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-attend/$eventId': {
      id: '/event-attend/$eventId'
      path: '/event-attend/$eventId'
      fullPath: '/event-attend/$eventId'
      preLoaderRoute: typeof EventAttendEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AnnouncementsLazyRoute: AnnouncementsLazyRoute,
  AttendanceLazyRoute: AttendanceLazyRoute,
  CampusLazyRoute: CampusLazyRoute,
  ClubsLazyRoute: ClubsLazyRoute,
  CookiesLazyRoute: CookiesLazyRoute,
  HelpLazyRoute: HelpLazyRoute,
  MyPassLazyRoute: MyPassLazyRoute,
  PrivacyLazyRoute: PrivacyLazyRoute,
  ScheduleLazyRoute: ScheduleLazyRoute,
  TermsLazyRoute: TermsLazyRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  EventAttendEventIdRoute: EventAttendEventIdRoute,
  AdminActivityLazyRoute: AdminActivityLazyRoute,
  AdminAnnouncementsLazyRoute: AdminAnnouncementsLazyRoute,
  AdminAttendanceLazyRoute: AdminAttendanceLazyRoute,
  AdminClubsLazyRoute: AdminClubsLazyRoute,
  AdminDatasetsLazyRoute: AdminDatasetsLazyRoute,
  AdminEventsLazyRoute: AdminEventsLazyRoute,
  AdminLoginLazyRoute: AdminLoginLazyRoute,
  AdminMediaLazyRoute: AdminMediaLazyRoute,
  AdminRoomsLazyRoute: AdminRoomsLazyRoute,
  AdminScheduleLazyRoute: AdminScheduleLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
